"""One-time OAuth helper that writes google-ads.yaml."""

from __future__ import annotations

import argparse
from pathlib import Path

from google_auth_oauthlib.flow import InstalledAppFlow

from google_ads_mcp.config import default_state_dir

SCOPE = ["https://www.googleapis.com/auth/adwords"]

YAML_TEMPLATE = """# Generated by google-ads-mcp-auth. Keep this file private.
developer_token: {developer_token}
client_id: {client_id}
client_secret: {client_secret}
refresh_token: {refresh_token}
use_proto_plus: True
{login_line}
"""


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Obtain a Google Ads OAuth refresh token.")
    parser.add_argument("--client-id", required=True, help="OAuth desktop client ID")
    parser.add_argument("--client-secret", required=True, help="OAuth desktop client secret")
    parser.add_argument("--developer-token", required=True, help="Google Ads developer token")
    parser.add_argument("--login-customer-id", help="MCC / manager customer ID, digits only")
    parser.add_argument(
        "--output",
        type=Path,
        default=default_state_dir() / "google-ads.yaml",
        help="Where to write google-ads.yaml",
    )
    args = parser.parse_args(argv)

    flow = InstalledAppFlow.from_client_config(
        {
            "installed": {
                "client_id": args.client_id,
                "client_secret": args.client_secret,
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "redirect_uris": ["http://localhost"],
            }
        },
        scopes=SCOPE,
    )
    credentials = flow.run_local_server(port=0)
    login_line = (
        f"login_customer_id: {args.login_customer_id}" if args.login_customer_id else ""
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        YAML_TEMPLATE.format(
            developer_token=args.developer_token,
            client_id=args.client_id,
            client_secret=args.client_secret,
            refresh_token=credentials.refresh_token,
            login_line=login_line,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {args.output}")
    print("Point GOOGLE_ADS_CONFIGURATION_FILE_PATH at this file, or copy it to ./google-ads.yaml")


if __name__ == "__main__":
    main()
